// Auto-generated migration declarations
// This file is generated by build.rs - do not edit manually

mod migration_001_initial_schema {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/db/migrations/001_initial_schema.rs"));
}
mod migration_002_add_host_config_columns {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/db/migrations/002_add_host_config_columns.rs"));
}
mod migration_003_add_smb_servers_table {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/db/migrations/003_add_smb_servers_table.rs"));
}
mod migration_004_fix_host_info_id_column {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/db/migrations/004_fix_host_info_id_column.rs"));
}


const MIGRATIONS: &[Migration] = &[
    Migration {
        version: 1,
        name: "initial_schema",
        up: migration_001_initial_schema::up,
        down: None,
    },
    Migration {
        version: 2,
        name: "add_host_config_columns",
        up: migration_002_add_host_config_columns::up,
        down: Some(migration_002_add_host_config_columns::down),
    },
    Migration {
        version: 3,
        name: "add_smb_servers_table",
        up: migration_003_add_smb_servers_table::up,
        down: Some(migration_003_add_smb_servers_table::down),
    },
    Migration {
        version: 4,
        name: "fix_host_info_id_column",
        up: migration_004_fix_host_info_id_column::up,
        down: Some(migration_004_fix_host_info_id_column::down),
    },

];
