name: Build Rust CLI
description: Build Rust CLI binary for a specific target

inputs:
  target:
    description: "Rust target triple"
    required: true
  skip_target:
    description: "Whether to skip this target build"
    required: false
    default: "false"
  unset_macos_deployment_target:
    description: "Unset MACOSX_DEPLOYMENT_TARGET (for macOS builds)"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Build Rust CLI
      shell: bash
      run: |
        if [ "${{ inputs.skip_target }}" == "true" ]; then
          echo "⚠️  Skipping build for ${{ inputs.target }} - target skipped"
          exit 0
        fi

        if [ "${{ inputs.target }}" == "aarch64-unknown-linux-musl" ]; then
          if [ "$SKIP_TARGET" == "true" ]; then
            echo "⚠️  Skipping aarch64-unknown-linux-musl - toolchain not available"
            exit 0
          elif command -v aarch64-linux-musl-gcc &> /dev/null; then
            echo "Using aarch64-linux-musl-gcc for build"
            cargo build --release --target ${{ inputs.target }}
          else
            echo "⚠️  aarch64-linux-musl-gcc not found, skipping build"
            exit 0
          fi
        else
          if [ "${{ inputs.unset_macos_deployment_target }}" == "true" ]; then
            unset MACOSX_DEPLOYMENT_TARGET || true
          fi
          cargo build --release --target ${{ inputs.target }}
        fi
      env:
        SKIP_TARGET: ${{ env.SKIP_TARGET }}
