name: Build Rust CLI
description: Build Rust CLI binary for a specific target

inputs:
  target:
    description: "Rust target triple"
    required: true
  skip_target:
    description: "Whether to skip this target build"
    required: false
    default: "false"
  unset_macos_deployment_target:
    description: "Unset MACOSX_DEPLOYMENT_TARGET (for macOS builds)"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Build Rust CLI
      shell: bash
      run: |
        # Verify cargo is available
        if ! command -v cargo &> /dev/null; then
          echo "❌ Error: cargo not found in PATH"
          echo "PATH: $PATH"
          echo "Checking for cargo in common locations..."
          ls -la ~/.cargo/bin/ 2>/dev/null || echo "~/.cargo/bin/ does not exist"
          exit 1
        fi

        echo "Using cargo: $(which cargo)"
        echo "Cargo version: $(cargo --version)"

        if [ "${{ inputs.skip_target }}" == "true" ]; then
          echo "⚠️  Skipping build for ${{ inputs.target }} - target skipped"
          exit 0
        fi

        # Temporarily disabled - toolchain download issues
        # if [ "${{ inputs.target }}" == "aarch64-unknown-linux-musl" ]; then
        #   # Check if we should skip based on input
        #   if [ "${{ inputs.skip_target }}" == "true" ]; then
        #     echo "⚠️  Skipping aarch64-unknown-linux-musl - target marked to skip"
        #     exit 0
        #   fi
        #   
        #   # Check if toolchain is available via environment variable
        #   if [ "$SKIP_TARGET" == "true" ]; then
        #     echo "⚠️  Skipping aarch64-unknown-linux-musl - toolchain not available"
        #     exit 0
        #   fi
        #   
        #   # Ensure PATH includes the toolchain location if it was set
        #   if [ -n "${MUSL_CROSS_DIR:-}" ] && [ -d "${MUSL_CROSS_DIR}/bin" ]; then
        #     export PATH="${MUSL_CROSS_DIR}/bin:$PATH"
        #     echo "Added ${MUSL_CROSS_DIR}/bin to PATH"
        #   fi
        #   
        #   # Check if the compiler is in PATH
        #   if command -v aarch64-linux-musl-gcc &> /dev/null; then
        #     echo "Using aarch64-linux-musl-gcc for build"
        #     echo "Compiler path: $(which aarch64-linux-musl-gcc)"
        #     echo "Compiler version: $(aarch64-linux-musl-gcc --version | head -1)"
        #     cargo build --release --target ${{ inputs.target }}
        #   # Check if toolchain exists in expected location
        #   elif [ -f "$HOME/musl-cross/bin/aarch64-linux-musl-gcc" ]; then
        #     export PATH="$HOME/musl-cross/bin:$PATH"
        #     echo "Found toolchain in $HOME/musl-cross/bin, added to PATH"
        #     echo "Compiler path: $(which aarch64-linux-musl-gcc)"
        #     cargo build --release --target ${{ inputs.target }}
        #   else
        #     echo "⚠️  aarch64-linux-musl-gcc not found"
        #     echo "PATH: $PATH"
        #     echo "MUSL_CROSS_DIR: ${MUSL_CROSS_DIR:-not set}"
        #     echo "Checking $HOME/musl-cross/bin..."
        #     ls -la "$HOME/musl-cross/bin/" 2>/dev/null || echo "Directory does not exist"
        #     echo "⚠️  Toolchain not found, skipping build"
        #     exit 0
        #   fi
        # else
          if [ "${{ inputs.unset_macos_deployment_target }}" == "true" ]; then
            unset MACOSX_DEPLOYMENT_TARGET || true
          fi
          cargo build --release --target ${{ inputs.target }}
        fi
      env:
        SKIP_TARGET: ${{ env.SKIP_TARGET }}
        MUSL_CROSS_DIR: ${{ env.MUSL_CROSS_DIR }}
        PATH: ${{ env.PATH }}
