name: Create GitHub Release
description: Create or update a GitHub release

inputs:
  tag:
    description: "Release tag"
    required: true
  name:
    description: "Release name"
    required: true
  body:
    description: "Release body text"
    required: false
    default: |
      ## Release

      ### Downloads
      - See assets below for platform-specific binaries

      ---
      *This release was created automatically by the build workflows.*
  files:
    description: "File pattern to upload (e.g., hal-*-linux-*.tar.gz). Empty string to skip file upload."
    required: false
    default: ""
  prerelease:
    description: "Whether this is a prerelease"
    required: false
    default: "false"
  append_body:
    description: "Append to existing release body instead of overwriting"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Create or update release (with files)
      if: inputs.files != ''
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.name }}
        body: ${{ inputs.body }}
        files: ${{ inputs.files }}
        draft: false
        prerelease: ${{ inputs.prerelease }}
        append_body: ${{ inputs.append_body }}
    - name: Create or update release (without files)
      if: inputs.files == ''
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.name }}
        body: ${{ inputs.body }}
        draft: false
        prerelease: ${{ inputs.prerelease }}
        append_body: ${{ inputs.append_body }}
