name: Setup Docker Build Environment
description: Checkout code, setup Docker Buildx, and login to registry

inputs:
  registry:
    description: "Container registry (e.g., ghcr.io)"
    required: true
  image_name:
    description: "Image name (e.g., owner/repo)"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
