// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$DiscoveredHost { void* hostname; void* local_ip; void* tailscale_ip; void* tailscale_hostname; uint16_t agent_port; bool reachable; } __swift_bridge__$DiscoveredHost;
typedef struct __swift_bridge__$Option$DiscoveredHost { bool is_some; __swift_bridge__$DiscoveredHost val; } __swift_bridge__$Option$DiscoveredHost;
typedef struct __swift_bridge__$HostInfo { void* docker_version; bool tailscale_installed; bool portainer_installed; } __swift_bridge__$HostInfo;
typedef struct __swift_bridge__$Option$HostInfo { bool is_some; __swift_bridge__$HostInfo val; } __swift_bridge__$Option$HostInfo;
typedef struct HalvorClient HalvorClient;
void __swift_bridge__$HalvorClient$_free(void* self);

void* __swift_bridge__$Vec_HalvorClient$new(void);
void __swift_bridge__$Vec_HalvorClient$drop(void* vec_ptr);
void __swift_bridge__$Vec_HalvorClient$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_HalvorClient$pop(void* vec_ptr);
void* __swift_bridge__$Vec_HalvorClient$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_HalvorClient$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_HalvorClient$len(void* vec_ptr);
void* __swift_bridge__$Vec_HalvorClient$as_ptr(void* vec_ptr);

void* __swift_bridge__$HalvorClient$new(struct __private__OptionU16 agent_port);
struct __private__ResultPtrAndPtr __swift_bridge__$HalvorClient$discover_agents(void* self);
struct __private__ResultPtrAndPtr __swift_bridge__$HalvorClient$discover_via_tailscale(void* self);
struct __private__ResultPtrAndPtr __swift_bridge__$HalvorClient$discover_via_local_network(void* self);
struct __swift_bridge__$ResultBoolAndString __swift_bridge__$HalvorClient$ping_agent(void* self, void* host, uint16_t port);
struct __swift_bridge__$ResultHostInfoAndString __swift_bridge__$HalvorClient$get_host_info(void* self, void* host, uint16_t port);
struct __private__ResultPtrAndPtr __swift_bridge__$HalvorClient$execute_command(void* self, void* host, uint16_t port, void* command, void* args);
typedef enum __swift_bridge__$ResultBoolAndString$Tag {__swift_bridge__$ResultBoolAndString$ResultOk, __swift_bridge__$ResultBoolAndString$ResultErr} __swift_bridge__$ResultBoolAndString$Tag;
union __swift_bridge__$ResultBoolAndString$Fields {bool ok; void* err;};
typedef struct __swift_bridge__$ResultBoolAndString{__swift_bridge__$ResultBoolAndString$Tag tag; union __swift_bridge__$ResultBoolAndString$Fields payload;} __swift_bridge__$ResultBoolAndString;
typedef enum __swift_bridge__$ResultHostInfoAndString$Tag {__swift_bridge__$ResultHostInfoAndString$ResultOk, __swift_bridge__$ResultHostInfoAndString$ResultErr} __swift_bridge__$ResultHostInfoAndString$Tag;
union __swift_bridge__$ResultHostInfoAndString$Fields {struct __swift_bridge__$HostInfo ok; void* err;};
typedef struct __swift_bridge__$ResultHostInfoAndString{__swift_bridge__$ResultHostInfoAndString$Tag tag; union __swift_bridge__$ResultHostInfoAndString$Fields payload;} __swift_bridge__$ResultHostInfoAndString;


