name: Check Changed Files
description: Check if source or docker files have changed

inputs:
  src_paths:
    description: "Paths to check for source code changes (newline-separated)"
    required: false
    default: |
      src/**
      Cargo.toml
      Cargo.lock
  docker_paths:
    description: "Paths to check for docker changes (newline-separated)"
    required: false
    default: |
      openvpn-container/**

outputs:
  src:
    description: "Whether source files changed"
    value: ${{ steps.filter.outputs.src }}
  docker:
    description: "Whether docker files changed"
    value: ${{ steps.filter.outputs.docker }}

runs:
  using: composite
  steps:
    - name: Build filters
      id: build_filters
      shell: bash
      run: |
        {
          echo 'src:'
          echo "${{ inputs.src_paths }}" | grep -v '^$' | sed "s/^/  - '/; s/\$/'/"
          echo 'docker:'
          echo "${{ inputs.docker_paths }}" | grep -v '^$' | sed "s/^/  - '/; s/\$/'/"
        } > /tmp/filters.txt

        {
          echo 'filters<<EOF'
          cat /tmp/filters.txt
          echo 'EOF'
        } >> $GITHUB_OUTPUT

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ${{ steps.build_filters.outputs.filters }}
