name: Check Changed Files
description: Check if source or docker files have changed

inputs:
  src_paths:
    description: "Paths to check for source code changes (newline-separated)"
    required: false
    default: |
      src/**
      Cargo.toml
      Cargo.lock
  docker_paths:
    description: "Paths to check for docker changes (newline-separated)"
    required: false
    default: |
      openvpn-container/**

outputs:
  src:
    description: "Whether source files changed"
    value: ${{ steps.filter.outputs.src }}
  docker:
    description: "Whether docker files changed"
    value: ${{ steps.filter.outputs.docker }}

runs:
  using: composite
  steps:
    - name: Build filters
      id: build_filters
      shell: bash
      run: |
        # Format each path as a YAML list item with quotes
        echo "src:" > /tmp/filters.txt
        echo "${{ inputs.src_paths }}" | while IFS= read -r line; do
          [ -n "$line" ] && echo "          - '$line'" >> /tmp/filters.txt
        done
        echo "        docker:" >> /tmp/filters.txt
        echo "${{ inputs.docker_paths }}" | while IFS= read -r line; do
          [ -n "$line" ] && echo "          - '$line'" >> /tmp/filters.txt
        done

        # Output filters as multiline string
        {
          echo 'filters<<EOF'
          cat /tmp/filters.txt
          echo 'EOF'
        } >> $GITHUB_OUTPUT

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ${{ steps.build_filters.outputs.filters }}
