// WASM module loader
// This will be replaced with the actual WASM module once built
import type { HalvorWasmModule } from './generated-bindings';

let wasmModule: HalvorWasmModule | null = null;

export async function loadWasmModule(): Promise<HalvorWasmModule> {
  if (wasmModule) {
    return wasmModule;
  }

  try {
    // Try to load the WASM module
    // This will be generated by wasm-pack build (outputs to this directory)
    const module = await import('./halvor_ffi_wasm.js');
    wasmModule = module as HalvorWasmModule;
    return wasmModule;
  } catch (error) {
    console.warn('WASM module not found, using mock implementation:', error);
    // Return a mock implementation for development
    return {
      discoverAgents: async () => {
        console.warn('WASM module not loaded - returning empty array');
        return [];
      },
      discoverViaTailscale: async () => [],
      discoverViaLocalNetwork: async () => [],
      pingAgent: async () => false,
      getHostInfo: async () => ({
        dockerVersion: undefined,
        tailscaleInstalled: false,
        portainerInstalled: false,
      }),
      executeCommand: async () => '',
    };
  }
}

// Default export for dynamic import
export default loadWasmModule;
