name: Release CLI
description: Complete release workflow for CLI binaries (get version, download artifacts, prepare archives, determine type, create release)

inputs:
  version_input:
    description: "Manual version input (optional)"
    required: false
    default: ""
  platform:
    description: "Platform (linux, darwin, windows)"
    required: true
  binary_name:
    description: "Binary name (hal or hal.exe)"
    required: true
  archive_extension:
    description: "Archive extension (.tar.gz or .zip)"
    required: true
  event_name:
    description: "GitHub event name"
    required: true
  experimental_input:
    description: "Experimental input flag"
    required: false
    default: "false"
  release_body:
    description: "Custom release body (optional)"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version
      id: version
      uses: ./.github/actions/get-version
      with:
        version_input: ${{ inputs.version_input }}

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Prepare release archives
      id: prepare
      uses: ./.github/actions/prepare-release-archives
      with:
        version: ${{ steps.version.outputs.version }}
        platform: ${{ inputs.platform }}
        binary_name: ${{ inputs.binary_name }}
        archive_extension: ${{ inputs.archive_extension }}

    - name: Determine release type
      id: release_type
      uses: ./.github/actions/determine-release-type
      with:
        event_name: ${{ inputs.event_name }}
        experimental_input: ${{ inputs.experimental_input }}
        version: ${{ steps.version.outputs.version }}

    - name: Generate install scripts
      id: install_scripts
      shell: bash
      run: |
        PLATFORM="${{ inputs.platform }}"
        TAG="${{ steps.release_type.outputs.tag }}"
        REPO="scottdkey/homelab"
        REGISTRY="ghcr.io"
        IMAGE_NAME="scottdkey/pia-vpn"
        IS_EXPERIMENTAL="${{ steps.release_type.outputs.type == 'experimental' && 'true' || 'false' }}"

        # Determine Docker image tags
        if [ "$IS_EXPERIMENTAL" == "true" ]; then
          DOCKER_TAG="experimental"
          DOCKER_PULL_LINES="docker pull ${REGISTRY}/${IMAGE_NAME}:experimental"
        else
          VERSION="${{ steps.version.outputs.version }}"
          SHORT_SHA="$(echo '${{ github.sha }}' | head -c 6)"
          DOCKER_PULL_LINES="docker pull ${REGISTRY}/${IMAGE_NAME}:latest
        docker pull ${REGISTRY}/${IMAGE_NAME}:${VERSION}
        docker pull ${REGISTRY}/${IMAGE_NAME}:${SHORT_SHA}"
        fi

        if [ "$PLATFORM" == "linux" ]; then
          PLATFORM_DISPLAY="Linux"
          printf '%s\n' \
            '### Linux CLI' \
            '' \
            '#### Install on Linux:' \
            '\`\`\`bash' \
            '# Download and install (latest)' \
            'curl -fsSL https://raw.githubusercontent.com/REPO_PLACEHOLDER/main/scripts/install.sh | bash' \
            '' \
            '# Or install specific version' \
            'curl -fsSL https://raw.githubusercontent.com/REPO_PLACEHOLDER/main/scripts/install.sh | bash -s TAG_PLACEHOLDER' \
            '\`\`\`' \
            '' \
            '#### Docker Image:' \
            '\`\`\`bash' \
            'DOCKER_TAGS_PLACEHOLDER' \
            '\`\`\`' > /tmp/install_script.txt
        elif [ "$PLATFORM" == "darwin" ]; then
          PLATFORM_DISPLAY="macOS"
          printf '%s\n' \
            '### macOS CLI' \
            '' \
            '#### Install on macOS:' \
            '\`\`\`bash' \
            '# Download and install (latest)' \
            'curl -fsSL https://raw.githubusercontent.com/REPO_PLACEHOLDER/main/scripts/install.sh | bash' \
            '' \
            '# Or install specific version' \
            'curl -fsSL https://raw.githubusercontent.com/REPO_PLACEHOLDER/main/scripts/install.sh | bash -s TAG_PLACEHOLDER' \
            '\`\`\`' \
            '' \
            '#### Docker Image:' \
            '\`\`\`bash' \
            'DOCKER_TAGS_PLACEHOLDER' \
            '\`\`\`' > /tmp/install_script.txt
        elif [ "$PLATFORM" == "windows" ]; then
          PLATFORM_DISPLAY="Windows"
          printf '%s\n' \
            '### Windows CLI' \
            '' \
            '#### Install on Windows (PowerShell):' \
            '\`\`\`powershell' \
            '# Download and install (latest)' \
            'irm https://raw.githubusercontent.com/REPO_PLACEHOLDER/main/scripts/install.ps1 | iex' \
            '' \
            '# Or install specific version' \
            'irm https://raw.githubusercontent.com/REPO_PLACEHOLDER/main/scripts/install.ps1 | iex -ArgumentList TAG_PLACEHOLDER' \
            '\`\`\`' \
            '' \
            '#### Docker Image:' \
            '\`\`\`bash' \
            'DOCKER_TAGS_PLACEHOLDER' \
            '\`\`\`' > /tmp/install_script.txt
        else
          echo "" > /tmp/install_script.txt
        fi

        # Replace placeholders (including escaped backticks)
        sed -i "s|REPO_PLACEHOLDER|${REPO}|g" /tmp/install_script.txt
        sed -i "s|TAG_PLACEHOLDER|${TAG}|g" /tmp/install_script.txt
        sed -i "s|DOCKER_TAGS_PLACEHOLDER|${DOCKER_PULL_LINES}|g" /tmp/install_script.txt
        # Replace escaped backticks with actual backticks
        sed -i 's|\\`\\`\\`|```|g' /tmp/install_script.txt

        echo "script<<EOF" >> $GITHUB_OUTPUT
        cat /tmp/install_script.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Check if platform content already exists in release
      id: check_existing
      shell: bash
      run: |
        TAG="${{ steps.release_type.outputs.tag }}"
        PLATFORM="${{ inputs.platform }}"

        # Determine platform display name
        if [ "$PLATFORM" == "linux" ]; then
          PLATFORM_DISPLAY="Linux"
        elif [ "$PLATFORM" == "darwin" ]; then
          PLATFORM_DISPLAY="macOS"
        else
          PLATFORM_DISPLAY="Windows"
        fi

        PLATFORM_MARKER="### ${PLATFORM_DISPLAY} CLI"

        # Try to fetch existing release body
        EXISTING_BODY=$(curl -s \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${TAG}" \
          | jq -r '.body // ""' 2>/dev/null || echo "")

        if [ -n "$EXISTING_BODY" ] && echo "$EXISTING_BODY" | grep -qF "$PLATFORM_MARKER"; then
          echo "Platform content already exists in release body"
          echo "should_append=false" >> $GITHUB_OUTPUT
        else
          echo "Platform content not found, will append"
          echo "should_append=true" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      uses: ./.github/actions/create-release
      with:
        tag: ${{ steps.release_type.outputs.tag }}
        name: ${{ steps.release_type.outputs.name }}
        body: ${{ inputs.release_body != '' && inputs.release_body || steps.install_scripts.outputs.script }}
        files: ${{ steps.prepare.outputs.archive_pattern }}
        prerelease: ${{ steps.release_type.outputs.prerelease }}
        append_body: ${{ steps.check_existing.outputs.should_append }}
